name: ScriptCalling
 
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    
jobs:
  update-json:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
     - name: Checkout files
       uses: Bhacaz/checkout-files@v2
       with:
         files: update-and-encrypt.ps1
     - name: Download and update nsi.json with secrets
       env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            prod_API_KEY: ${{ secrets.API_KEY }}
            run: update-and-encrypt.ps1
       
       
